name: Deploy to Server

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 68.183.179.31 >> ~/.ssh/known_hosts

      - name: Deploy Code
        run: |
          ssh vc-ssh@68.183.179.31 << 'EOF'
          cd /home/sostarghor-vc/htdocs/vc.sostarghor.com
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          chmod -R 775 storage bootstrap/cache
          EOF
